data_scraper:
  root_url: https://pokemondb.net/
  data_url: https://pokemondb.net/pokedex/all
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
  timeout: 100
  clear_contents: True
  scraped_data_path: data/external/scraped_pokemons.csv

data_processor:
  scraped_data_path: data/external/scraped_pokemons.csv
  database_path: data/database/pokemon_stats.db